name: SAM Package
description: Build and package using SAM

inputs:
  aws-access-key-id:
    description: AWS Access Key ID
    required: true

  aws-region:
    description: AWS Region
    required: true

  aws-secret-access-key:
    description: AWS Secret Access Key
    required: true

  bucket:
    description: S3 bucket name
    required: true

  ref:
    description: Git Ref to package
    required: false
    default: ''

  requirements:
    description: Python Requirements
    required: false
    default: requirements.txt

  stack-name:
    description: Name of the stack folder
    required: true

outputs:
  bucket:
    description: Target bucket name
    value: ${{ inputs.bucket }}

  stack-name:
    description: Exported stack name
    value: ${{ inputs.stack-name }}

  template:
    description: Template file name
    value: ${{ inputs.stack-name }}-template

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.ref }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: pip

    - name: Setup SAM
      uses: aws-actions/setup-sam@v1
      with:
        version: 1.40.1

    - name: Install dependencies
      if: inputs.requirements
      working-directory: ${{ inputs.stack-name }}
      run: pip install -r ${{ inputs.requirements }}
      shell: bash

    - name: Cache build
      uses: actions/cache@v2
      with:
        path: ${{ inputs.stack-name }}/.aws-sam
        key: ${{ runner.os }}-${{ inputs.stack-name }}-sam-package

    - name: Build
      working-directory: ${{ inputs.stack-name }}
      run: >-
        sam build --cached --parallel
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Prepare Output Directory
      working-directory: ${{ inputs.stack-name }}
      run: mkdir .packaged
      shell: bash

    - name: Package
      working-directory: ${{ inputs.stack-name }}
      run: |
        sam package \
          --region ${{ inputs.aws-region }} \
          --s3-bucket ${{ inputs.bucket }} \
          --s3-prefix ${{ inputs.stack-name }} \
          --output-template-file .packaged/template.yaml
      shell: bash

    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.stack-name }}-template
        path: ${{ inputs.stack-name }}/.packaged/template.yaml
